import { generatedMissingItems } from './generated-missing-items';

export interface Item {
  id: string;
  name: string;
  category: 'arc_parts' | 'crafting_materials' | 'quest_items' | 'recyclable' | 'consumables';
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  action: 'keep' | 'sell' | 'recycle';
  value: number;
  image: string;
  description: string;
  usedFor?: string[];
  recyclesInto?: string[];
}

const baseItems: Item[] = [
  // ARC Parts - Keep for Quests/Crafting
  {
    id: 'free_loadout_augment',
    name: 'Free Loadout Augment',
    category: 'arc_parts',
    rarity: 'common',
    action: 'keep',
    value: 100,
    image: 'https://arcraiders.wiki/w/images/c/cf/Free_Loadout_Augment.png',
    description:
      'Basic augment from free loadouts that increases carry capacity: +14 backpack slots, +4 quest slots, +2 weapon slots while only weighing 1 kg.',
    usedFor: ['Starter loadout capacity boost', 'Scavenged augments'],
  },
  {
    id: 'leaper_pulse_unit',
    name: 'Leaper Pulse Unit',
    category: 'arc_parts',
    rarity: 'epic',
    action: 'keep',
    value: 5000,
    image: '/items/leaper_pulse_unit.png',
    description: 'Quest: Into the Fray (x1) • Workshop: Utility Station L3 (x4)',
    usedFor: ['Quest: Into the Fray', 'Workshop: Utility Station L3'],
  },
  {
    id: 'rocketeer_driver',
    name: 'Rocketeer Driver',
    category: 'arc_parts',
    rarity: 'epic',
    action: 'keep',
    value: 5000,
    image: '/items/rocketeer_driver.png',
    description: 'Quest: Out of the Shadows (x1) • Workshop: Explosives Station L3 (x3)',
    usedFor: ['Quest: Out of the Shadows', 'Workshop: Explosives Station L3'],
  },
  {
    id: 'surveyor_vault',
    name: 'Surveyor Vault',
    category: 'arc_parts',
    rarity: 'rare',
    action: 'keep',
    value: 2000,
    image: '/items/surveyor_vault.png',
    description: 'Quest: Mixed Signals (x1) • Workshop: Medical Lab L3 (x5)',
    usedFor: ['Quest: Mixed Signals', 'Workshop: Medical Lab L3'],
  },
  {
    id: 'hornet_driver',
    name: 'Hornet Driver',
    category: 'arc_parts',
    rarity: 'rare',
    action: 'keep',
    value: 2000,
    image: '/items/hornet_driver.png',
    description: 'Quest: The Trifecta (x2) • Workshop: Gear Bench L2 (x5)',
    usedFor: ['Quest: The Trifecta', 'Workshop: Gear Bench L2'],
  },
  {
    id: 'wasp_driver',
    name: 'Wasp Driver',
    category: 'arc_parts',
    rarity: 'rare',
    action: 'keep',
    value: 1000,
    image: '/items/wasp_driver.png',
    description: 'Quest: The Trifecta (x2) • Workshop: Gunsmith L2 (x8)',
    usedFor: ['Quest: The Trifecta', 'Workshop: Gunsmith L2'],
  },
  {
    id: 'snitch_scanner',
    name: 'Snitch Scanner',
    category: 'arc_parts',
    rarity: 'rare',
    action: 'keep',
    value: 780,
    image: '/items/snitch_scanner.png',
    description: 'Detection array from Snitch units. Critical for security system upgrades.',
    usedFor: ['Security Station', 'Alarm System'],
  },
  {
    id: 'spotter_relay',
    name: 'Spotter Relay',
    category: 'arc_parts',
    rarity: 'uncommon',
    action: 'keep',
    value: 550,
    image: '/items/spotter_relay.png',
    description: 'Communication relay from Spotter drones. Enhances team coordination systems.',
    usedFor: ['Communication Hub', 'Team Coordination'],
  },

  // Crafting Materials - Keep
  {
    id: 'arc_alloy',
    name: 'ARC Alloy',
    category: 'crafting_materials',
    rarity: 'rare',
    action: 'keep',
    value: 450,
    image: '/items/arc_alloy.png',
    description: 'Refined metal alloy from ARC technology. Primary material for weapon and armor crafting.',
    usedFor: ['Weapon Crafting', 'Armor Upgrades', 'Hideout Construction'],
  },
  {
    id: 'advanced_electrical_components',
    name: 'Advanced Electrical Components',
    category: 'crafting_materials',
    rarity: 'rare',
    action: 'keep',
    value: 1750,
    image: '/items/advanced_electrical_components.png',
    description: 'High-grade electronic parts. Essential for advanced equipment and power systems.',
    usedFor: ['Generator Upgrade', 'Electronic Devices', 'Power Systems'],
  },
  {
    id: 'exodus_modules',
    name: 'Exodus Modules',
    category: 'crafting_materials',
    rarity: 'epic',
    action: 'keep',
    value: 980,
    image: '/items/exodus_modules.png',
    description: 'Pre-invasion technology modules. Rare and valuable for top-tier crafting.',
    usedFor: ['Legendary Weapon Crafting', 'Hideout Level 4'],
  },
  {
    id: 'magnetic_accelerator',
    name: 'Magnetic Accelerator',
    category: 'crafting_materials',
    rarity: 'rare',
    action: 'keep',
    value: 720,
    image: '/items/magnetic_accelerator.png',
    description: 'Electromagnetic propulsion device. Used in railgun and energy weapon crafting.',
    usedFor: ['Energy Weapons', 'Railgun Crafting'],
  },
  {
    id: 'sensors',
    name: 'Sensors',
    category: 'crafting_materials',
    rarity: 'uncommon',
    action: 'keep',
    value: 280,
    image: '/items/sensors.png',
    description: 'Detection sensors for various applications. Common crafting component.',
    usedFor: ['Scopes', 'Detection Equipment', 'Traps'],
  },
  {
    id: 'battery',
    name: 'Battery',
    category: 'crafting_materials',
    rarity: 'common',
    action: 'keep',
    value: 120,
    image: '/items/battery.png',
    description: 'Portable power source. Needed for electronic devices and equipment.',
    usedFor: ['Flashlights', 'Electronic Devices', 'Power Tools'],
  },
  {
    id: 'electrical_components',
    name: 'Electrical Components',
    category: 'crafting_materials',
    rarity: 'common',
    action: 'keep',
    value: 150,
    image: '/items/electrical_components.png',
    description: 'Basic electronic parts. Fundamental crafting material.',
    usedFor: ['Basic Electronics', 'Repairs', 'Modifications'],
  },
  {
    id: 'wires',
    name: 'Wires',
    category: 'crafting_materials',
    rarity: 'common',
    action: 'keep',
    value: 80,
    image: '/items/wires.png',
    description: 'Copper wiring for electrical connections. Always useful.',
    usedFor: ['Electrical Repairs', 'Crafting', 'Hideout Wiring'],
  },
  {
    id: 'durable_cloth',
    name: 'Durable Cloth',
    category: 'crafting_materials',
    rarity: 'uncommon',
    action: 'keep',
    value: 200,
    image: '/items/durable_cloth.png',
    description: 'Reinforced fabric material. Used in armor and gear crafting.',
    usedFor: ['Armor Crafting', 'Backpacks', 'Tactical Gear'],
  },
  {
    id: 'steel_spring',
    name: 'Steel Spring',
    category: 'crafting_materials',
    rarity: 'uncommon',
    action: 'keep',
    value: 180,
    image: '/items/steel_spring.png',
    description: 'High-tension steel springs. Mechanical crafting component.',
    usedFor: ['Weapon Mechanisms', 'Traps', 'Mechanical Devices'],
  },
  {
    id: 'rubber_parts',
    name: 'Rubber Parts',
    category: 'crafting_materials',
    rarity: 'common',
    action: 'keep',
    value: 90,
    image: '/items/rubber_parts.png',
    description: 'Flexible rubber components. Useful for seals and grips.',
    usedFor: ['Weapon Grips', 'Seals', 'Shock Absorption'],
  },
  {
    id: 'metal_parts',
    name: 'Metal Parts',
    category: 'crafting_materials',
    rarity: 'common',
    action: 'keep',
    value: 110,
    image: '/items/metal_parts.png',
    description: 'Assorted metal components. Basic crafting material.',
    usedFor: ['Weapon Parts', 'Repairs', 'Construction'],
  },
  {
    id: 'fabric',
    name: 'Fabric',
    category: 'crafting_materials',
    rarity: 'common',
    action: 'keep',
    value: 70,
    image: '/items/fabric.png',
    description: 'Basic cloth material. Common crafting resource.',
    usedFor: ['Bandages', 'Clothing', 'Bags'],
  },
  {
    id: 'plastic_parts',
    name: 'Plastic Parts',
    category: 'crafting_materials',
    rarity: 'common',
    action: 'keep',
    value: 60,
    image: '/items/plastic_parts.png',
    description: 'Molded plastic components. Lightweight crafting material.',
    usedFor: ['Containers', 'Weapon Furniture', 'Equipment'],
  },

  // Quest Items - Always Keep
  {
    id: 'antiseptic',
    name: 'Antiseptic',
    category: 'quest_items',
    rarity: 'rare',
    action: 'keep',
    value: 1000,
    image: '/items/antiseptic.png',
    description: 'Used to craft: Medical Lab: Sterilized Bandage',
    usedFor: ['Medical Lab: Sterilized Bandage'],
  },
  {
    id: 'syringe',
    name: 'Syringe',
    category: 'quest_items',
    rarity: 'rare',
    action: 'keep',
    value: 5000,
    image: '/items/syringe.png',
    description: 'Quest: Doctor\'s Orders (x1)',
    usedFor: ['Quest: Doctor\'s Orders'],
  },
  {
    id: 'water_pump',
    name: 'Water Pump',
    category: 'quest_items',
    rarity: 'rare',
    action: 'keep',
    value: 650,
    image: '/items/water_pump.png',
    description: 'Mechanical water extraction device. Critical for water system quest.',
    usedFor: ['Water System Quest', 'Hideout Water Supply'],
  },
  {
    id: 'humidifier',
    name: 'Humidifier',
    category: 'quest_items',
    rarity: 'uncommon',
    action: 'keep',
    value: 380,
    image: '/items/humidifier.png',
    description: 'Air moisture control device. Required for air quality quest.',
    usedFor: ['Air Quality Quest', 'Hideout Comfort'],
  },
  {
    id: 'cooling_fan',
    name: 'Cooling Fan',
    category: 'quest_items',
    rarity: 'uncommon',
    action: 'keep',
    value: 290,
    image: '/items/cooling_fan.png',
    description: 'Ventilation equipment. Needed for cooling system quest.',
    usedFor: ['Cooling System Quest', 'Generator Cooling'],
  },
  {
    id: 'light_bulb',
    name: 'Light Bulb',
    category: 'quest_items',
    rarity: 'common',
    action: 'keep',
    value: 150,
    image: '/items/light_bulb.png',
    description: 'Illumination device. Required for lighting system quest.',
    usedFor: ['Lighting Quest', 'Hideout Illumination'],
  },
  {
    id: 'power_rod',
    name: 'Power Rod',
    category: 'quest_items',
    rarity: 'epic',
    action: 'keep',
    value: 5500,
    image: '/items/power_rod.png',
    description: 'Used to craft: Gear Bench: Heavy Shield • Utility Station: Snap Hook',
    usedFor: ['Gear Bench: Heavy Shield', 'Utility Station: Snap Hook'],
  },

  // Recyclable Items - Recycle for Materials
  {
    id: 'broken_flashlight',
    name: 'Broken Flashlight',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 45,
    image: '/items/broken_flashlight.png',
    description: 'Damaged lighting device. Recycle for electrical components.',
    recyclesInto: ['Electrical Components', 'Battery', 'Plastic Parts'],
  },
  {
    id: 'broken_handheld_radio',
    name: 'Broken Handheld Radio',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 55,
    image: '/items/broken_handheld_radio.png',
    description: 'Non-functional communication device. Recycle for electronics.',
    recyclesInto: ['Electrical Components', 'Wires', 'Metal Parts'],
  },
  {
    id: 'damaged_arc_powercell',
    name: 'Damaged ARC Powercell',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 180,
    image: '/items/damaged_arc_powercell.png',
    description: 'Depleted ARC energy cell. Recycle for advanced materials.',
    recyclesInto: ['Advanced Electrical Components', 'Battery', 'ARC Alloy'],
  },
  {
    id: 'burned_arc_circuitry',
    name: 'Burned ARC Circuitry',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 160,
    image: '/items/burned_arc_circuitry.png',
    description: 'Fried electronic circuits. Recycle for salvageable components.',
    recyclesInto: ['Electrical Components', 'Wires', 'Metal Parts'],
  },
  {
    id: 'ruined_accordion',
    name: 'Ruined Accordion',
    category: 'recyclable',
    rarity: 'common',
    action: 'sell',
    value: 120,
    image: '/items/ruined_accordion.png',
    description: 'Destroyed musical instrument. Sell for credits or recycle for metal.',
    recyclesInto: ['Metal Parts', 'Steel Spring'],
  },
  {
    id: 'alarm_clock',
    name: 'Alarm Clock',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 65,
    image: '/items/alarm_clock.png',
    description: 'Old timepiece. Recycle for small mechanical parts.',
    recyclesInto: ['Metal Parts', 'Wires', 'Battery'],
  },
  {
    id: 'bicycle_pump',
    name: 'Bicycle Pump',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 70,
    image: '/items/bicycle_pump.png',
    description: 'Manual air pump. Recycle for rubber and metal.',
    recyclesInto: ['Rubber Parts', 'Metal Parts'],
  },
  {
    id: 'broken_taser',
    name: 'Broken Taser',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 140,
    image: '/items/broken_taser.png',
    description: 'Non-functional stun weapon. Recycle for electrical components.',
    recyclesInto: ['Electrical Components', 'Battery', 'Plastic Parts'],
  },
  {
    id: 'camera_lens',
    name: 'Camera Lens',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 190,
    image: '/items/camera_lens.png',
    description: 'Optical glass component. Recycle for sensors.',
    recyclesInto: ['Sensors', 'Plastic Parts'],
  },
  {
    id: 'candle_holder',
    name: 'Candle Holder',
    category: 'recyclable',
    rarity: 'common',
    action: 'sell',
    value: 95,
    image: '/items/candle_holder.png',
    description: 'Decorative metal holder. Better to sell than recycle.',
    recyclesInto: ['Metal Parts'],
  },
  {
    id: 'deflated_football',
    name: 'Deflated Football',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 40,
    image: '/items/deflated_football.png',
    description: 'Punctured sports ball. Recycle for rubber.',
    recyclesInto: ['Rubber Parts'],
  },
  {
    id: 'diving_goggles',
    name: 'Diving Goggles',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 85,
    image: '/items/diving_goggles.png',
    description: 'Swimming eyewear. Recycle for rubber and plastic.',
    recyclesInto: ['Rubber Parts', 'Plastic Parts'],
  },
  {
    id: 'expired_respirator',
    name: 'Expired Respirator',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 130,
    image: '/items/expired_respirator.png',
    description: 'Old gas mask. Recycle for rubber and filters.',
    recyclesInto: ['Rubber Parts', 'Fabric', 'Plastic Parts'],
  },
  {
    id: 'geiger_counter',
    name: 'Geiger Counter',
    category: 'recyclable',
    rarity: 'epic',
    action: 'recycle',
    value: 3500,
    image: 'https://arcraiders.wiki/w/images/3/37/Geiger_Counter.png',
    description: 'Epic radiation detector found in Exodus caches. Weighs 1.5, stacks to 3, and can be recycled into premium crafting materials or sold for 3,500 credits.',
  },
  {
    id: 'ion_sputter',
    name: 'Ion Sputter',
    category: 'recyclable',
    rarity: 'epic',
    action: 'recycle',
    value: 6000,
    image: 'https://arcraiders.wiki/w/images/e/e7/Ion_Sputter.png',
    description: 'High-grade ARC tool dropped in Exodus loot. 1.5 weight, stack size 3, and worth 6,000 credits if you sell instead of recycling for crafting parts.',
  },
  {
    id: 'spectrum_analyzer',
    name: 'Spectrum Analyzer',
    category: 'recyclable',
    rarity: 'epic',
    action: 'recycle',
    value: 3500,
    image: 'https://arcraiders.wiki/w/images/thumb/a/a5/Spectrum_Analyzer.png/150px-Spectrum_Analyzer.png',
    description: 'Epic scavenged item found in Exodus regions (Medical Research, Assembly, Lobby Metro, Sandbox). Weighs 1.5 kg, stacks to 3. Recycles into Exodus Modules x1 and Sensors x1 (total value 3,250 CR).',
    recyclesInto: ['Exodus Modules', 'Sensors'],
  },
  {
    id: 'rusted_gears',
    name: 'Rusted Gears',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 640,
    image: 'https://arcraiders.wiki/w/images/thumb/5/58/Rusted_Gear.png/150px-Rusted_Gear.png',
    description: 'Found in vehicles, generators, and industrial containers on Dam Battlegrounds, Spaceport, and Blue Gate (especially Warehouse Complex). Best farming route: Buried City car park at Marano Station.',
    recyclesInto: ['Metal Parts', 'Steel Spring'],
  },
  {
    id: 'dog_collar',
    name: 'Dog Collar',
    category: 'quest_items',
    rarity: 'rare',
    action: 'keep',
    value: 640,
    image: 'https://arcraiders.wiki/w/images/thumb/a/ab/Dog_Collar.png/150px-Dog_Collar.png',
    description: 'Rare recyclable found in residential areas (bins, desks) on Buried City and Spaceport. Used to upgrade Scrappy I → Scrappy II at Workshop, increasing loot quality from Scrappy between raids.',
    usedFor: ['Workshop: Scrappy L2 (x1)'],
  },
  {
    id: 'industrial_battery',
    name: 'Industrial Battery',
    category: 'quest_items',
    rarity: 'rare',
    action: 'keep',
    value: 1000,
    image: 'https://arcraiders.wiki/w/images/thumb/0/04/Industrial_Battery.png/150px-Industrial_Battery.png',
    description: 'Found on steel shelves in industrial zones. Best locations: Dam Battlegrounds (Hydroponic Dome, Control Tower), Blue Gate (Warehouse), Spaceport (Rocket Assembly). Required for Gear Bench L3 upgrade (x3).',
    usedFor: ['Workshop: Gear Bench L3 (x3)'],
    recyclesInto: ['Battery', 'Chemicals'],
  },
  {
    id: 'frying_pan',
    name: 'Frying Pan',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 75,
    image: '/items/frying_pan.png',
    description: 'Cooking utensil. Recycle for metal.',
    recyclesInto: ['Metal Parts'],
  },
  {
    id: 'garlic_press',
    name: 'Garlic Press',
    category: 'recyclable',
    rarity: 'common',
    action: 'sell',
    value: 50,
    image: '/items/garlic_press.png',
    description: 'Kitchen tool. Low value, sell or recycle.',
    recyclesInto: ['Metal Parts'],
  },
  {
    id: 'headphones',
    name: 'Headphones',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 90,
    image: '/items/headphones.png',
    description: 'Audio equipment. Recycle for wires and plastic.',
    recyclesInto: ['Wires', 'Plastic Parts', 'Metal Parts'],
  },
  {
    id: 'ice_cream_scooper',
    name: 'Ice Cream Scooper',
    category: 'recyclable',
    rarity: 'common',
    action: 'sell',
    value: 45,
    image: '/items/ice_cream_scooper.png',
    description: 'Kitchen utensil. Minimal value.',
    recyclesInto: ['Metal Parts'],
  },
  {
    id: 'portable_tv',
    name: 'Portable TV',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 220,
    image: '/items/portable_tv.png',
    description: 'Small television. Good source of electronics.',
    recyclesInto: ['Electrical Components', 'Wires', 'Plastic Parts', 'Sensors'],
  },
  {
    id: 'power_bank',
    name: 'Power Bank',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 170,
    image: '/items/power_bank.png',
    description: 'Portable charger. Recycle for batteries.',
    recyclesInto: ['Battery', 'Electrical Components', 'Plastic Parts'],
  },
  {
    id: 'projector',
    name: 'Projector',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 250,
    image: '/items/projector.png',
    description: 'Display device. Rich source of components.',
    recyclesInto: ['Electrical Components', 'Sensors', 'Wires', 'Plastic Parts'],
  },
  {
    id: 'remote_control',
    name: 'Remote Control',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 60,
    image: '/items/remote_control.png',
    description: 'Device controller. Recycle for electronics.',
    recyclesInto: ['Electrical Components', 'Battery', 'Plastic Parts'],
  },
  {
    id: 'ruined_baton',
    name: 'Ruined Baton',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 80,
    image: '/items/ruined_baton.png',
    description: 'Broken melee weapon. Recycle for metal and rubber.',
    recyclesInto: ['Metal Parts', 'Rubber Parts'],
  },
  {
    id: 'ruined_parachute',
    name: 'Ruined Parachute',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 150,
    image: '/items/ruined_parachute.png',
    description: 'Torn parachute. Good source of fabric.',
    recyclesInto: ['Fabric', 'Durable Cloth'],
  },
  {
    id: 'rusted_bolts',
    name: 'Rusted Bolts',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 35,
    image: '/items/rusted_bolts.png',
    description: 'Corroded fasteners. Minimal value.',
    recyclesInto: ['Metal Parts'],
  },
  {
    id: 'tattered_clothes',
    name: 'Tattered Clothes',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 30,
    image: '/items/tattered_clothes.png',
    description: 'Worn clothing. Recycle for fabric.',
    recyclesInto: ['Fabric'],
  },
  {
    id: 'thermostat',
    name: 'Thermostat',
    category: 'recyclable',
    rarity: 'uncommon',
    action: 'recycle',
    value: 140,
    image: '/items/thermostat.png',
    description: 'Temperature control device. Recycle for electronics.',
    recyclesInto: ['Electrical Components', 'Sensors', 'Plastic Parts'],
  },
  {
    id: 'torn_blanket',
    name: 'Torn Blanket',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 50,
    image: '/items/torn_blanket.png',
    description: 'Damaged bedding. Recycle for fabric.',
    recyclesInto: ['Fabric'],
  },
  {
    id: 'toaster',
    name: 'Toaster',
    category: 'recyclable',
    rarity: 'common',
    action: 'recycle',
    value: 95,
    image: '/items/toaster.png',
    description: 'Kitchen appliance. Recycle for metal and wires.',
    recyclesInto: ['Metal Parts', 'Wires', 'Steel Spring'],
  },

  // Consumables - Use or Sell
  {
    id: 'lemon',
    name: 'Lemon',
    category: 'consumables',
    rarity: 'common',
    action: 'sell',
    value: 25,
    image: '/items/lemon.png',
    description: 'Fresh citrus fruit. Sell for quick credits.',
  },
  {
    id: 'apricot',
    name: 'Apricot',
    category: 'consumables',
    rarity: 'common',
    action: 'sell',
    value: 30,
    image: '/items/apricot.png',
    description: 'Dried fruit. Sell for credits.',
  },
  {
    id: 'dog_collar',
    name: 'Dog Collar',
    category: 'recyclable',
    rarity: 'common',
    action: 'sell',
    value: 40,
    image: '/items/dog_collar.png',
    description: 'Pet accessory. Minimal value, sell.',
    recyclesInto: ['Fabric', 'Metal Parts'],
  },
];

export const items: Item[] = [...baseItems, ...(generatedMissingItems as Item[])];

export const categories = [
  { id: 'all', name: 'All Items', count: items.length },
  { id: 'arc_parts', name: 'ARC Parts', count: items.filter(i => i.category === 'arc_parts').length },
  { id: 'crafting_materials', name: 'Crafting Materials', count: items.filter(i => i.category === 'crafting_materials').length },
  { id: 'quest_items', name: 'Quest Items', count: items.filter(i => i.category === 'quest_items').length },
  { id: 'recyclable', name: 'Recyclable', count: items.filter(i => i.category === 'recyclable').length },
  { id: 'consumables', name: 'Consumables', count: items.filter(i => i.category === 'consumables').length },
];

/* export const actions = [
  { id: 'all', name: 'All Actions', icon: '📋' },
  { id: 'keep', name: 'Keep', icon: '✅', color: 'green' },
  { id: 'sell', name: 'Sell', icon: '💰', color: 'yellow' },
  { id: 'recycle', name: 'Recycle', icon: '♻️', color: 'blue' },
]; */

export const rarities = [
  { id: 'all', name: 'All Rarities' },
  { id: 'common', name: 'Common', color: '#9CA3AF' },
  { id: 'uncommon', name: 'Uncommon', color: '#10B981' },
  { id: 'rare', name: 'Rare', color: '#3B82F6' },
  { id: 'epic', name: 'Epic', color: '#8B5CF6' },
  { id: 'legendary', name: 'Legendary', color: '#F59E0B' },
];
