// Arc Raiders Complete Skill Tree Data
// Source: ARCTracker.io (Nov 2025 Update)

export interface Skill {
  id: string;
  name: string;
  tree: 'mobility' | 'survival' | 'conditioning';
  tier: number; // 1-7, where 1 is base and 7 is capstone
  maxPoints: number;
  icon: string;
  description: string;
  position: 'left' | 'center' | 'right';
  isCapstone?: boolean;
  requires?: string[]; // Skill IDs that must be unlocked first
}

export const allSkills: Skill[] = [
  // MOBILITY TREE (Yellow)
  {
    id: 'mob_1',
    name: 'Nimble Climber',
    tree: 'mobility',
    tier: 1,
    maxPoints: 5,
    icon: '/skills/nimble_climber.png',
    description: 'Increases climbing speed. Essential for vertical navigation on large maps.',
    position: 'center',
  },
  {
    id: 'mob_2l',
    name: 'Marathon Runner',
    tree: 'mobility',
    tier: 2,
    maxPoints: 5,
    icon: '/skills/marathon_runner.png',
    description: 'Increases sprint duration. Each point adds 1.5 seconds of sprint time.',
    position: 'left',
  },
  {
    id: 'mob_2r',
    name: 'Slip and Slide',
    tree: 'mobility',
    tier: 2,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/slip_and_slide.png',
    description: 'Reduces slide stamina cost. Maintain momentum while sliding.',
    position: 'right',
  },
  {
    id: 'mob_3l',
    name: 'Youthful Lungs',
    tree: 'mobility',
    tier: 3,
    maxPoints: 5,
    icon: '/skills/youthful_lungs.png',
    description: 'Increases stamina regeneration rate. Critical for sustained mobility.',
    position: 'left',
  },
  {
    id: 'mob_3r',
    name: 'Sturdy Ankles',
    tree: 'mobility',
    tier: 3,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/sturdy_ankles.png',
    description: 'Reduces fall damage. Survive higher drops without injury.',
    position: 'right',
  },
  {
    id: 'mob_4l',
    name: 'Carry the Momentum',
    tree: 'mobility',
    tier: 4,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/carry_the_momentum.png',
    description: 'Sprint immediately after vaulting without stamina penalty.',
    position: 'left',
  },
  {
    id: 'mob_4r',
    name: 'Calming Stroll',
    tree: 'mobility',
    tier: 4,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/calming_stroll.png',
    description: 'Regenerate stamina faster while walking.',
    position: 'right',
  },
  {
    id: 'mob_5c',
    name: 'Crawl Before You Walk',
    tree: 'mobility',
    tier: 5,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/crawl_before_you_walk.png',
    description: 'Increases crouch-walking speed.',
    position: 'center',
  },
  {
    id: 'mob_5l',
    name: 'Effortless Roll',
    tree: 'mobility',
    tier: 5,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/effortless_roll.png',
    description: 'Reduces dodge roll stamina cost.',
    position: 'left',
  },
  {
    id: 'mob_5r',
    name: 'Off the Wall',
    tree: 'mobility',
    tier: 5,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/off_the_wall.png',
    description: 'Wall-running duration increased.',
    position: 'right',
  },
  {
    id: 'mob_6c',
    name: 'Vigorous Vaulter',
    tree: 'mobility',
    tier: 6,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/vigorous_vaulter.png',
    description: 'Vaulting no longer costs stamina.',
    position: 'center',
  },
  {
    id: 'mob_6l',
    name: 'Heroic Leap',
    tree: 'mobility',
    tier: 6,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/heroic_leap.png',
    description: 'Increases jump height and distance.',
    position: 'left',
  },
  {
    id: 'mob_6r',
    name: 'Ready to Roll',
    tree: 'mobility',
    tier: 6,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/ready_to_roll.png',
    description: 'Reduces dodge roll cooldown.',
    position: 'right',
  },
  {
    id: 'mob_7l',
    name: 'Vaults on Vaults on Vaults',
    tree: 'mobility',
    tier: 7,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/vaults_on_vaults_on_vaults.png',
    description: 'Chain vaults without delay. Ultimate parkour freedom.',
    position: 'left',
    isCapstone: true,
  },
  {
    id: 'mob_7r',
    name: 'Vault Spring',
    tree: 'mobility',
    tier: 7,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/vault_spring.png',
    description: 'Gain brief speed boost after vaulting.',
    position: 'right',
    isCapstone: true,
  },

  // SURVIVAL TREE (Red)
  {
    id: 'surv_1',
    name: 'Agile Croucher',
    tree: 'survival',
    tier: 1,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/agile_croucher.png',
    description: 'Increases crouch-walking speed for stealth movement.',
    position: 'center',
  },
  {
    id: 'surv_2l',
    name: "Looter's Instincts",
    tree: 'survival',
    tier: 2,
    maxPoints: 5,
    icon: '/skills/looters_instincts.png',
    description: 'Highlights nearby loot. Essential for efficient looting.',
    position: 'left',
  },
  {
    id: 'surv_2r',
    name: 'Revitalizing Squat',
    tree: 'survival',
    tier: 2,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/revitalizing_squat.png',
    description: 'Regenerate health faster while crouched.',
    position: 'right',
  },
  {
    id: 'surv_3l',
    name: 'Silent Scavenger',
    tree: 'survival',
    tier: 3,
    maxPoints: 5,
    icon: '/skills/silent_scavenger.png',
    description: 'Reduces looting noise. Loot quietly without alerting enemies.',
    position: 'left',
  },
  {
    id: 'surv_3r',
    name: 'In-Round Crafting',
    tree: 'survival',
    tier: 3,
    maxPoints: 1,
    icon: '/skills/in_round_crafting.png',
    description: 'Unlock ability to craft bandages, shield rechargers, and ammo mid-raid. ESSENTIAL skill.',
    position: 'right',
  },
  {
    id: 'surv_4l',
    name: 'Suffer in Silence',
    tree: 'survival',
    tier: 4,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/suffer_in_silence.png',
    description: 'Healing makes less noise.',
    position: 'left',
  },
  {
    id: 'surv_4r',
    name: 'Good as New',
    tree: 'survival',
    tier: 4,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/good_as_new.png',
    description: 'Healing items restore more health.',
    position: 'right',
  },
  {
    id: 'surv_5c',
    name: 'Traveling Tinkerer',
    tree: 'survival',
    tier: 5,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/traveling_tinkerer.png',
    description: 'Craft while moving (slowly).',
    position: 'center',
  },
  {
    id: 'surv_5l',
    name: 'Broad Shoulders',
    tree: 'survival',
    tier: 5,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/broad_shoulders.png',
    description: 'Increases carrying capacity. Each point = +2kg.',
    position: 'left',
  },
  {
    id: 'surv_5r',
    name: 'Stubborn Mule',
    tree: 'survival',
    tier: 5,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/stubborn_mule.png',
    description: 'Reduces movement penalty when overencumbered.',
    position: 'right',
  },
  {
    id: 'surv_6c',
    name: "One Raider's Scraps",
    tree: 'survival',
    tier: 6,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/one_raiders_scraps.png',
    description: 'Chance to get bonus crafting materials when recycling.',
    position: 'center',
  },
  {
    id: 'surv_6l',
    name: "Looter's Luck",
    tree: 'survival',
    tier: 6,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/looters_luck.png',
    description: 'Increased loot quality in containers.',
    position: 'left',
  },
  {
    id: 'surv_6r',
    name: 'Three Deep Breaths',
    tree: 'survival',
    tier: 6,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/three_deep_breaths.png',
    description: 'Out-of-combat health regeneration increased.',
    position: 'right',
  },
  {
    id: 'surv_7l',
    name: 'Security Breach',
    tree: 'survival',
    tier: 7,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/security_breach.png',
    description: 'Unlock security lockers faster.',
    position: 'left',
    isCapstone: true,
  },
  {
    id: 'surv_7r',
    name: 'Minesweeper',
    tree: 'survival',
    tier: 7,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/minesweeper.png',
    description: 'Detect and disarm mines more easily.',
    position: 'right',
    isCapstone: true,
  },

  // CONDITIONING TREE (Green)
  {
    id: 'cond_1',
    name: 'Used to the Weight',
    tree: 'conditioning',
    tier: 1,
    maxPoints: 5,
    icon: '/skills/used_to_the_weight.png',
    description: 'Reduces movement penalty from heavy gear. Essential for loadout flexibility.',
    position: 'center',
  },
  {
    id: 'cond_2l',
    name: 'Blast Born',
    tree: 'conditioning',
    tier: 2,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/blast_born.png',
    description: 'Reduces explosive damage taken.',
    position: 'left',
  },
  {
    id: 'cond_2r',
    name: 'Gentle Pressure',
    tree: 'conditioning',
    tier: 2,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/gentle_pressure.png',
    description: 'Reduces recoil when firing weapons.',
    position: 'right',
  },
  {
    id: 'cond_3l',
    name: 'Fight or Flight',
    tree: 'conditioning',
    tier: 3,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/fight_or_flight.png',
    description: 'Movement speed increases briefly when taking damage.',
    position: 'left',
  },
  {
    id: 'cond_3r',
    name: 'Proficient Pryer',
    tree: 'conditioning',
    tier: 3,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/proficient_pryer.png',
    description: 'Open crates and containers faster.',
    position: 'right',
  },
  {
    id: 'cond_4l',
    name: "Survivor's Stamina",
    tree: 'conditioning',
    tier: 4,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/survivors_stamina.png',
    description: 'Stamina regenerates while being revived.',
    position: 'left',
  },
  {
    id: 'cond_4r',
    name: 'Unburdened Roll',
    tree: 'conditioning',
    tier: 4,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/unburdened_roll.png',
    description: 'Dodge roll distance unaffected by gear weight.',
    position: 'right',
  },
  {
    id: 'cond_5c',
    name: 'A Little Extra',
    tree: 'conditioning',
    tier: 5,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/a_little_extra.png',
    description: 'Gain extra ammo on weapon pickup.',
    position: 'center',
  },
  {
    id: 'cond_5l',
    name: 'Downed but Determined',
    tree: 'conditioning',
    tier: 5,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/downed_but_determined.png',
    description: 'Move faster while downed.',
    position: 'left',
  },
  {
    id: 'cond_5r',
    name: 'Effortless Swing',
    tree: 'conditioning',
    tier: 5,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/effortless_swing.png',
    description: 'Melee attacks cost less stamina.',
    position: 'right',
  },
  {
    id: 'cond_6c',
    name: 'Loaded Arms',
    tree: 'conditioning',
    tier: 6,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/loaded_arms.png',
    description: 'Increased starting ammo for all weapons.',
    position: 'center',
  },
  {
    id: 'cond_6l',
    name: 'Turtle Crawl',
    tree: 'conditioning',
    tier: 6,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/turtle_crawl.png',
    description: 'Downed crawling speed increased.',
    position: 'left',
  },
  {
    id: 'cond_6r',
    name: 'Sky Clearing Swing',
    tree: 'conditioning',
    tier: 6,
    maxPoints: 5,
    icon: 'https://cdn.arctracker.io/skillnodes/sky_clearing_swing.png',
    description: 'Melee attacks deal more damage.',
    position: 'right',
  },
  {
    id: 'cond_7l',
    name: 'Back on Your Feet',
    tree: 'conditioning',
    tier: 7,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/back_on_your_feet.png',
    description: 'Faster revive time for teammates reviving you.',
    position: 'left',
    isCapstone: true,
  },
  {
    id: 'cond_7r',
    name: 'Flyswatter',
    tree: 'conditioning',
    tier: 7,
    maxPoints: 1,
    icon: 'https://cdn.arctracker.io/skillnodes/flyswatter.png',
    description: 'Melee attacks can deflect enemy projectiles.',
    position: 'right',
    isCapstone: true,
  },
];

// Helper function to get skills by tree
export function getSkillsByTree(tree: 'mobility' | 'survival' | 'conditioning'): Skill[] {
  return allSkills.filter(skill => skill.tree === tree);
}

// Helper function to get skills by tier
export function getSkillsByTier(tier: number): Skill[] {
  return allSkills.filter(skill => skill.tier === tier);
}

// Total skill points available
export const MAX_SKILL_POINTS = 75;

// Tree colors
export const TREE_COLORS = {
  mobility: '#fdd333', // Yellow
  survival: '#f4101b', // Red
  conditioning: '#2afe7f', // Green
};
